Feat/Add valkey performance testing terraform configs
3scale-sre/valkey-performance-testing pull request #1
Opened 2024-10-29 12:45 UTC by slopezz

The PR publishes the work done at https://github.com/3scale/platform/issues/1450 regarding performance tests of valkey/redis on AWS EC2/Elasticache.
- Adding terraform configs
- Adding a README with the configuration applied, and the commans to run each server (valkey/redis) or valkey-benchmark tool

2024-10-30 11:30 UTC, raelga approved these changes

2024-10-30 12:14 UTC, roivaz requested changes

2024-10-30 12:14 UTC, roivaz commented on settings.tf
> +  }
remove this?

2024-10-30 15:28 UTC, slopezz commented on settings.tf
> +  }
Solved on latest force-push

2024-10-30 15:32 UTC, raelga approved these changes

2024-10-31 10:45 UTC, roivaz approved these changes

2024-10-31 10:55 UTC, slopezz commented
/approve

2024-10-31 10:55 UTC, slopezz commented
/approve

2024-10-31 10:57 UTC, merged